name = "sweet-daisies-orchestra"
compatibility_date = "2024-10-05"

[env.production]
name = "sweet-daisies-orchestra"

[[env.production.routes]]
pattern = "sweet-daisies-orchestra.com"
zone_name = "sweet-daisies-orchestra.com"

[[env.production.routes]]
pattern = "www.sweet-daisies-orchestra.com"
zone_name = "sweet-daisies-orchestra.com"

[build]
command = ""
publish = "./"

[vars]
ENVIRONMENT = "production"